/**
 *
 *  Settings.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Settings.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Settings::Cols::_id = "id";
const std::string Settings::Cols::_delete_interval_num = "delete_interval_num";
const std::string Settings::Cols::_delete_interval_unit = "delete_interval_unit";
const std::string Settings::Cols::_is_enable_delete = "is_enable_delete";
const std::string Settings::primaryKeyName = "id";
const bool Settings::hasPrimaryKey = true;
const std::string Settings::tableName = "settings";

const std::vector<typename Settings::MetaData> Settings::metaData_={
{"id","uint64_t","integer",8,1,1,1},
{"delete_interval_num","uint64_t","integer",8,0,0,0},
{"delete_interval_unit","std::string","text",0,0,0,0},
{"is_enable_delete","uint64_t","integer",8,0,0,0}
};
const std::string &Settings::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Settings::Settings(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<uint64_t>(r["id"].as<uint64_t>());
        }
        if(!r["delete_interval_num"].isNull())
        {
            deleteIntervalNum_=std::make_shared<uint64_t>(r["delete_interval_num"].as<uint64_t>());
        }
        if(!r["delete_interval_unit"].isNull())
        {
            deleteIntervalUnit_=std::make_shared<std::string>(r["delete_interval_unit"].as<std::string>());
        }
        if(!r["is_enable_delete"].isNull())
        {
            isEnableDelete_=std::make_shared<uint64_t>(r["is_enable_delete"].as<uint64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            deleteIntervalNum_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            deleteIntervalUnit_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            isEnableDelete_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
    }

}

Settings::Settings(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            deleteIntervalNum_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            deleteIntervalUnit_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            isEnableDelete_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
}

Settings::Settings(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("delete_interval_num"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["delete_interval_num"].isNull())
        {
            deleteIntervalNum_=std::make_shared<uint64_t>((uint64_t)pJson["delete_interval_num"].asUInt64());
        }
    }
    if(pJson.isMember("delete_interval_unit"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["delete_interval_unit"].isNull())
        {
            deleteIntervalUnit_=std::make_shared<std::string>(pJson["delete_interval_unit"].asString());
        }
    }
    if(pJson.isMember("is_enable_delete"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["is_enable_delete"].isNull())
        {
            isEnableDelete_=std::make_shared<uint64_t>((uint64_t)pJson["is_enable_delete"].asUInt64());
        }
    }
}

void Settings::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            deleteIntervalNum_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            deleteIntervalUnit_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            isEnableDelete_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
}

void Settings::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("delete_interval_num"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["delete_interval_num"].isNull())
        {
            deleteIntervalNum_=std::make_shared<uint64_t>((uint64_t)pJson["delete_interval_num"].asUInt64());
        }
    }
    if(pJson.isMember("delete_interval_unit"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["delete_interval_unit"].isNull())
        {
            deleteIntervalUnit_=std::make_shared<std::string>(pJson["delete_interval_unit"].asString());
        }
    }
    if(pJson.isMember("is_enable_delete"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["is_enable_delete"].isNull())
        {
            isEnableDelete_=std::make_shared<uint64_t>((uint64_t)pJson["is_enable_delete"].asUInt64());
        }
    }
}

const uint64_t &Settings::getValueOfId() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Settings::getId() const noexcept
{
    return id_;
}
void Settings::setId(const uint64_t &pId) noexcept
{
    id_ = std::make_shared<uint64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Settings::PrimaryKeyType & Settings::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const uint64_t &Settings::getValueOfDeleteIntervalNum() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(deleteIntervalNum_)
        return *deleteIntervalNum_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Settings::getDeleteIntervalNum() const noexcept
{
    return deleteIntervalNum_;
}
void Settings::setDeleteIntervalNum(const uint64_t &pDeleteIntervalNum) noexcept
{
    deleteIntervalNum_ = std::make_shared<uint64_t>(pDeleteIntervalNum);
    dirtyFlag_[1] = true;
}
void Settings::setDeleteIntervalNumToNull() noexcept
{
    deleteIntervalNum_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Settings::getValueOfDeleteIntervalUnit() const noexcept
{
    const static std::string defaultValue = std::string();
    if(deleteIntervalUnit_)
        return *deleteIntervalUnit_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Settings::getDeleteIntervalUnit() const noexcept
{
    return deleteIntervalUnit_;
}
void Settings::setDeleteIntervalUnit(const std::string &pDeleteIntervalUnit) noexcept
{
    deleteIntervalUnit_ = std::make_shared<std::string>(pDeleteIntervalUnit);
    dirtyFlag_[2] = true;
}
void Settings::setDeleteIntervalUnit(std::string &&pDeleteIntervalUnit) noexcept
{
    deleteIntervalUnit_ = std::make_shared<std::string>(std::move(pDeleteIntervalUnit));
    dirtyFlag_[2] = true;
}
void Settings::setDeleteIntervalUnitToNull() noexcept
{
    deleteIntervalUnit_.reset();
    dirtyFlag_[2] = true;
}

const uint64_t &Settings::getValueOfIsEnableDelete() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(isEnableDelete_)
        return *isEnableDelete_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Settings::getIsEnableDelete() const noexcept
{
    return isEnableDelete_;
}
void Settings::setIsEnableDelete(const uint64_t &pIsEnableDelete) noexcept
{
    isEnableDelete_ = std::make_shared<uint64_t>(pIsEnableDelete);
    dirtyFlag_[3] = true;
}
void Settings::setIsEnableDeleteToNull() noexcept
{
    isEnableDelete_.reset();
    dirtyFlag_[3] = true;
}

void Settings::updateId(const uint64_t id)
{
    id_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string> &Settings::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "delete_interval_num",
        "delete_interval_unit",
        "is_enable_delete"
    };
    return inCols;
}

void Settings::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDeleteIntervalNum())
        {
            binder << getValueOfDeleteIntervalNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDeleteIntervalUnit())
        {
            binder << getValueOfDeleteIntervalUnit();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getIsEnableDelete())
        {
            binder << getValueOfIsEnableDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Settings::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Settings::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDeleteIntervalNum())
        {
            binder << getValueOfDeleteIntervalNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDeleteIntervalUnit())
        {
            binder << getValueOfDeleteIntervalUnit();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getIsEnableDelete())
        {
            binder << getValueOfIsEnableDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Settings::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::UInt64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDeleteIntervalNum())
    {
        ret["delete_interval_num"]=(Json::UInt64)getValueOfDeleteIntervalNum();
    }
    else
    {
        ret["delete_interval_num"]=Json::Value();
    }
    if(getDeleteIntervalUnit())
    {
        ret["delete_interval_unit"]=getValueOfDeleteIntervalUnit();
    }
    else
    {
        ret["delete_interval_unit"]=Json::Value();
    }
    if(getIsEnableDelete())
    {
        ret["is_enable_delete"]=(Json::UInt64)getValueOfIsEnableDelete();
    }
    else
    {
        ret["is_enable_delete"]=Json::Value();
    }
    return ret;
}

Json::Value Settings::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::UInt64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDeleteIntervalNum())
            {
                ret[pMasqueradingVector[1]]=(Json::UInt64)getValueOfDeleteIntervalNum();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDeleteIntervalUnit())
            {
                ret[pMasqueradingVector[2]]=getValueOfDeleteIntervalUnit();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getIsEnableDelete())
            {
                ret[pMasqueradingVector[3]]=(Json::UInt64)getValueOfIsEnableDelete();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::UInt64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDeleteIntervalNum())
    {
        ret["delete_interval_num"]=(Json::UInt64)getValueOfDeleteIntervalNum();
    }
    else
    {
        ret["delete_interval_num"]=Json::Value();
    }
    if(getDeleteIntervalUnit())
    {
        ret["delete_interval_unit"]=getValueOfDeleteIntervalUnit();
    }
    else
    {
        ret["delete_interval_unit"]=Json::Value();
    }
    if(getIsEnableDelete())
    {
        ret["is_enable_delete"]=(Json::UInt64)getValueOfIsEnableDelete();
    }
    else
    {
        ret["is_enable_delete"]=Json::Value();
    }
    return ret;
}

bool Settings::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("delete_interval_num"))
    {
        if(!validJsonOfField(1, "delete_interval_num", pJson["delete_interval_num"], err, true))
            return false;
    }
    if(pJson.isMember("delete_interval_unit"))
    {
        if(!validJsonOfField(2, "delete_interval_unit", pJson["delete_interval_unit"], err, true))
            return false;
    }
    if(pJson.isMember("is_enable_delete"))
    {
        if(!validJsonOfField(3, "is_enable_delete", pJson["is_enable_delete"], err, true))
            return false;
    }
    return true;
}
bool Settings::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Settings::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("delete_interval_num"))
    {
        if(!validJsonOfField(1, "delete_interval_num", pJson["delete_interval_num"], err, false))
            return false;
    }
    if(pJson.isMember("delete_interval_unit"))
    {
        if(!validJsonOfField(2, "delete_interval_unit", pJson["delete_interval_unit"], err, false))
            return false;
    }
    if(pJson.isMember("is_enable_delete"))
    {
        if(!validJsonOfField(3, "is_enable_delete", pJson["is_enable_delete"], err, false))
            return false;
    }
    return true;
}
bool Settings::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Settings::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
